[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"
  environment = { NODE_VERSION = "14.19.0", NODE_ENV = "production" }

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[template.environment]
  ACKEE_MONGODB = mongodb+srv://Admin:isCJj8yqyYErkQY@bimonoanalytics.z99koll.mongodb.net/?retryWrites=true&w=majority
  ACKEE_USERNAME = AdminAckee
  ACKEE_PASSWORD = 08CEhDDD9MzUZbS
  ACKEE_ALLOW_ORIGIN = *.bimono.io
